-- ============================================
-- 전북로 DB 초기화 스크립트
-- Oracle 11g 기준
-- ============================================

-- 1. 기존 데이터 삭제 (필요시)
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER USERS_TRG';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE USERS_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE USERS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 2. 시퀀스 생성
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;

-- 3. 회원 테이블 생성
CREATE TABLE USERS (
    USER_ID     NUMBER PRIMARY KEY,
    PROVIDER    VARCHAR2(20)  NOT NULL,
    PROVIDER_ID VARCHAR2(100) NOT NULL,
    EMAIL       VARCHAR2(100),
    NICKNAME    VARCHAR2(30)  NOT NULL,
    PROFILE_IMG VARCHAR2(500),
    ROLE        VARCHAR2(10)  DEFAULT 'USER',
    CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP,
    NICKNAME_SET NUMBER(1)    DEFAULT 0 NOT NULL,
    CONSTRAINT uq_provider UNIQUE (PROVIDER, PROVIDER_ID)
);

-- 4. 닉네임 중복 방지 인덱스
CREATE UNIQUE INDEX IDX_USERS_NICKNAME ON USERS(NICKNAME);

-- 5. USER_ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER USERS_TRG
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    SELECT USERS_SEQ.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
END;
/

-- 6. 커밋
COMMIT;

-- 7. 테이블 확인
SELECT * FROM USERS;

-- ============================================
-- 유용한 관리 쿼리
-- ============================================

-- 8. 모든 사용자 조회
SELECT USER_ID, PROVIDER, NICKNAME, NICKNAME_SET, EMAIL, CREATED_AT 
FROM USERS 
ORDER BY USER_ID DESC;

-- 9. 특정 제공자별 사용자 조회
-- SELECT * FROM USERS WHERE PROVIDER = 'KAKAO';
-- SELECT * FROM USERS WHERE PROVIDER = 'GOOGLE';
-- SELECT * FROM USERS WHERE PROVIDER = 'NAVER';

-- 10. 특정 사용자의 닉네임 설정 상태 초기화 (다시 설정하고 싶을 때)
-- UPDATE USERS SET NICKNAME_SET = 0 WHERE PROVIDER = 'KAKAO' AND PROVIDER_ID = '1234567890';
-- COMMIT;

-- 11. 특정 사용자 삭제 (완전 초기화)
-- DELETE FROM USERS WHERE PROVIDER = 'KAKAO' AND PROVIDER_ID = '1234567890';
-- COMMIT;

-- 12. 테이블 컬럼 정보 확인
DESC USERS;

-- 13. 시퀀스 현재값 확인
SELECT USERS_SEQ.CURRVAL FROM DUAL;

-- 14. 닉네임 중복 확인
-- SELECT NICKNAME, COUNT(*) FROM USERS GROUP BY NICKNAME HAVING COUNT(*) > 1;

-- 15. 사용자 수 통계
SELECT PROVIDER, COUNT(*) AS COUNT 
FROM USERS 
GROUP BY PROVIDER;